server:
    port: 8090
spring:
    data:
        mongodb:
            username: rbattezzati
            password: rbattezzati
            host: localhost
            port: 27017
            database: customer
            authentication-database: admin

    kafka:
      producer:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
          spring.json.type.mapping: orderConfirmation:com.rbattezzati.ecommerce.kafka.OrderConfirmation