server:
    port: 8090
spring:
    data:
        mongodb:
            username: rbattezzati
            password: rbattezzati
            host: localhost
            port: 27017
            database: customer
            authentication-database: admin